# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-09 11:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180209_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='signature',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
