# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-09 11:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_signature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='signature',
        ),
    ]
